name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install pdf.js
        run: |
          npm install pdfjs-dist@4.2.67 --no-audit --no-fund
          mkdir -p pdfjs
          cp node_modules/pdfjs-dist/build/pdf.min.js pdfjs/
          cp node_modules/pdfjs-dist/build/pdf.worker.min.js pdfjs/
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: .
  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy
        id: deployment
        uses: actions/deploy-pages@v4
